### ISSUE TITLE
Job never start with Azure Cosmos Mongodb engine

### ISSUE THREAD

**Issue by kennethwwu** [agenda/agenda#1072]
"agenda": "^3.1.0"
Server Version: 3.2

jobs can be started and process as expected when connecting to local mongo, but never been started connect to Azure Cosmos, I have check the job data has been write to 'agendaJobs' correctly.

**Comment by jona0497** [comment]
Similar problem here. 
I've tried passing sort: { nextRunAt: 1 } as suggested under "known issues", but it doesn't seem to solve the problem for me. Has anyone had any success with this recently?

**Comment by simllll** [comment]
If you send me a connection string to a cosmos mongodb, I can offer you to debug it on my side.

**Comment by jona0497** [comment]
That’s very kind.
Can you please provide me an address where I can send a temporary connection string to?

**Comment by simllll** [comment]
simon.tretter@hokify.com

**Comment by simllll** [comment]
the database query fails,
```
DB FAILED MongoError: Error=2, Details='Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: 1a344157-4bec-4880-b816-2b79b16b2610; Reason: (Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: 1a344157-4bec-4880-b816-2b79b16b2610; Reason: (Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: 1a344157-4bec-4880-b816-2b79b16b2610; Reason: (Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: 1a344157-4bec-4880-b816-2b79b16b2610; Reason: (Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: 1a344157-4bec-4880-b816-2b79b16b2610; Reason: (Message: {"Errors":["The order by query does not have a corresponding composite index that it can be served from."]}
ActivityId: 1a344157-4bec-4880-b816-2b79b16b2610, Request URI: /apps/ea705b66-063a-48e6-9d26-f5ab2888d753/services/19c11863-73ae-41e3-82db-6e2a8d8b1e4f/partitions/65c74894-1869-4374-8d89-eff6ba78cdda/replicas/132479360084936715s/, RequestStats: Please see CosmosDiagnostics, SDK: Windows/10.0.14393 cosmos-netstandard-sdk/3.3.2);););););
    at Connection.<anonymous> (/home/simon/Dev/other/agenda-hokify/node_modules/mongodb/lib/core/connection/pool.js:451:61)
    at Connection.emit (events.js:315:20)
    at processMessage (/home/simon/Dev/other/agenda-hokify/node_modules/mongodb/lib/core/connection/connection.js:452:10)
    at TLSSocket.<anonymous> (/home/simon/Dev/other/agenda-hokify/node_modules/mongodb/lib/core/connection/connection.js:621:15)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at TLSSocket.Readable.push (_stream_readable.js:223:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23) {
  ok: 0,
  code: 2,
  codeName: 'BadValue'
}
```

adding an index works, at least with [@hokify/agenda](https://www.npmjs.com/package/@hokify/agenda).

I connected agenda with the following code:
```
import { connect } from 'mongodb';

const mongoDb = (await connect('connection string')).db();
agenda = new Agenda({
          mongo: mongoDb
        });
```
and ran following mongo query: `db.agendaJobs.ensureIndex({ nextRunAt: 1, priority: -1 })` to create the index.

So just try using the fork @hokify/agenda in the meantime, and set the index should do the trick!

**Comment by Baldassari** [comment]
I had the same issue and based on @simllll tip I could sove my problem.
```js
const { connect } = require('mongodb');
async start() {
  const mongoDb = (await connect(mongoConnectionString)).db();
  agenda = new Agenda({
    mongo: mongoDb
  });

  mongoDb.collection("agendaJobs").createIndexes({ nextRunAt: 1, priority: -1 });
  await agenda.start();
}
```

**Comment by allandiego** [comment]
having same behavior with azure cosmos db fixed with suggested index.

this is the default index created:
```sh
name_1_nextRunAt_1_priority_-1_lockedAt_1_disabled_1
```

fixed with the new index:
```js
const agenda = new Agenda(config);
await agenda._collection.createIndex({ nextRunAt: 1, priority: -1 });
```
