### ISSUE TITLE
Unhandled promise rejections are deprecated

### ISSUE THREAD

**Issue by Yuvod-Dev** [agenda/agenda#1075]
(node:77852) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:153:11)
    at processPromiseRejections (internal/process/promises.js:205:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)

**Comment by OmgImAlexis** [comment]
Where is this being thrown? I don’t see any stacktrace showing any of our code.

**Comment by Yuvod-Dev** [comment]
(node:99258) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'findOneAndUpdate' of undefined
    at Agenda.module.exports [as saveJob] (/Users/.../node_modules/agenda/lib/agenda/save-job.js:105:45)
    at Job.module.exports [as save] (/Users/.../node_modules/agenda/lib/job/save.js:13:22)
    at createJob (/Users/.../node_modules/agenda/lib/agenda/every.js:28:15)
    at Agenda.module.exports [as every] (/Users/.../node_modules/agenda/lib/agenda/every.js:55:24)
    at /Users/.../src/_lib/jobs/FetchEPG.js:19:18
    at Array.map (<anonymous>)
    at new FetchEPG (/Users/.../src/_lib/jobs/FetchEPG.js:13:29)
    at module.exports (/Users/.../src/_lib/jobs/FetchEPG.js:65:3)
    at /Users/.../src/_lib/CronJobs.js:11:28
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/.../src/_lib/CronJobs.js:10:10)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at emitUnhandledRejectionWarning (internal/process/promises.js:141:15)
    at processPromiseRejections (internal/process/promises.js:203:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
(node:99258) TypeError: Cannot read property 'findOneAndUpdate' of undefined
    at Agenda.module.exports [as saveJob] (/Users/.../node_modules/agenda/lib/agenda/save-job.js:105:45)
    at Job.module.exports [as save] (/Users/.../node_modules/agenda/lib/job/save.js:13:22)
    at createJob (/Users/.../node_modules/agenda/lib/agenda/every.js:28:15)
    at Agenda.module.exports [as every] (/Users/.../node_modules/agenda/lib/agenda/every.js:55:24)
    at /Users/.../src/_lib/jobs/FetchEPG.js:19:18
    at Array.map (<anonymous>)
    at new FetchEPG (/Users/.../src/_lib/jobs/FetchEPG.js:13:29)
    at module.exports (/Users/.../src/_lib/jobs/FetchEPG.js:65:3)
    at /Users/.../src/_lib/CronJobs.js:11:28
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/.../src/_lib/CronJobs.js:10:10)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
(node:99258) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:153:11)
    at processPromiseRejections (internal/process/promises.js:205:13)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
(node:99258) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'findOneAndUpdate' of undefined
    at Agenda.module.exports [as saveJob] (/Users/.../node_modules/agenda/lib/agenda/save-job.js:105:45)
    at Job.module.exports [as save] (/Users/.../node_modules/agenda/lib/job/save.js:13:22)
    at createJob (/Users/.../node_modules/agenda/lib/agenda/every.js:28:15)
    at Agenda.module.exports [as every] (/Users/.../node_modules/agenda/lib/agenda/every.js:55:24)
    at /Users/.../src/_lib/jobs/FetchEPG.js:19:18
    at Array.map (<anonymous>)
    at new FetchEPG (/Users/.../src/_lib/jobs/FetchEPG.js:13:29)
    at module.exports (/Users/.../src/_lib/jobs/FetchEPG.js:65:3)
    at /Users/.../src/_lib/CronJobs.js:11:28
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/.../src/_lib/CronJobs.js:10:10)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at emitUnhandledRejectionWarning (internal/process/promises.js:141:15)
    at processPromiseRejections (internal/process/promises.js:203:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
(node:99258) TypeError: Cannot read property 'findOneAndUpdate' of undefined
    at Agenda.module.exports [as saveJob] (/Users/.../node_modules/agenda/lib/agenda/save-job.js:105:45)
    at Job.module.exports [as save] (/Users/.../node_modules/agenda/lib/job/save.js:13:22)
    at createJob (/Users/.../node_modules/agenda/lib/agenda/every.js:28:15)
    at Agenda.module.exports [as every] (/Users/.../node_modules/agenda/lib/agenda/every.js:55:24)
    at /Users/.../src/_lib/jobs/FetchEPG.js:19:18
    at Array.map (<anonymous>)
    at new FetchEPG (/Users/.../src/_lib/jobs/FetchEPG.js:13:29)
    at module.exports (/Users/.../src/_lib/jobs/FetchEPG.js:65:3)
    at /Users/.../src/_lib/CronJobs.js:11:28
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/.../src/_lib/CronJobs.js:10:10)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
    at Module.require (internal/modules/cjs/loader.js:1016:19)

**Comment by OmgImAlexis** [comment]
Put back ticks around the code please.

**Comment by OmgImAlexis** [comment]
Looks like it's an issue with your code. It's throwing because the `_collection` property doesn't exist. Our code makes sure it does so it's something on your end.

You'll need to provide a reproducible code sample otherwise we can't really help.

**Comment by Yuvod-Dev** [comment]
CronJobs.js:
```
const
  Agenda = require('agenda')

const
  connectionOpts = {db: {address: process.env.MONGO_URL || APP.config.connectionString, collection: 'Jobs', options: { useUnifiedTopology: true }}},
  agenda = new Agenda(connectionOpts),
  jobTypes = process.env.JOB_TYPES ? process.env.JOB_TYPES.split(',') : ['FetchEPG']

// Load jobs
jobTypes.forEach(type => {
  require('./jobs/' + type)(agenda, 'Europe/Madrid')
})

// Init agenda
if (jobTypes.length) {
  agenda.start()
}

module.exports = agenda
```
FetchEPG.js:

```
class FetchEPG {

  constructor(CronJobs, timeZone = 'Europe/Madrid') {
    const _this = this
    this.timeZone = timeZone

    CronJobs.define('test1', async job => {
      await _this.test1('test-source')
    })
    CronJobs.every('6 hours', 'test1', {}, {
      timezone: this.timeZone
    })
  }

  async test1(source) {
    return new Promise(async (resolve, reject) => {
      setTimeout(function () {
        console.log('test1 job finished:', source)
        resolve()
      }, 2000)
    })
  }

}

module.exports = function(CronJobs, timeZone) {
  new FetchEPG(CronJobs, timeZone)
}
```
the 'Jobs' collection was created correctly in my db, but errors arise when you try to save the jobs, the truth is that I think it is rather an incompatibility with mongo 4.2.6, since some functions are deprecated, but I await your comments , Thank you so much!!

**Comment by alihuber** [comment]
I also got errors like `TypeError: Cannot read property 'findOneAndUpdate' of undefined` or `TypeError: Cannot read property '_nextScanAt' of undefined`.
I found that it had nothing to do with the version of mongodb, it was some misplaced code.
This minimal example kinda resembles your given code that will throw the same errors on mongob3.2, 4.0.2 and 4.2.6:
```
const Agenda = require('agenda');
const connectionOpts = { db: { address: 'localhost:27017/agenda-test' } };
const agenda = new Agenda(connectionOpts);

agenda.define('test1', async job => {
  await cronJob('test-source');
  console.log('done.');
});

const cronJob = (source) => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      console.log('resolve ', source)
      resolve();
    }, 2000);
  });
}

// this will throw the errors above
// agenda.start();
(async function () { // IIFE to give access to async/await
  await agenda.start();
  await agenda.every('1 minute', 'test1');
})();
// this will throw the errors above
// agenda.every('1 minute', 'test1');
```
In my case it was even more weird, because I was working with a meteor project that (normally) patches promises away, so other asynchronous code ran fine, but this did not.  
I think there might be something off with your code, since neither `agenda.start()` nor `agenda.every()` are wrapped in async/await.

**Comment by shruti9rk** [comment]
(node:5604) UnhandledPromiseRejectionWarning: MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at NativeConnection.Connection.openUri (D:\webDev\Secrets - Starting Code\node_modules\mongoose\lib\connection.js:832:32)
    at D:\webDev\Secrets - Starting Code\node_modules\mongoose\lib\index.js:345:10
    at D:\webDev\Secrets - Starting Code\node_modules\mongoose\lib\helpers\promiseOrCallback.js:31:5
    at new Promise (<anonymous>)
    at promiseOrCallback (D:\webDev\Secrets - Starting Code\node_modules\mongoose\lib\helpers\promiseOrCallback.js:30:10)
    at Mongoose._promiseOrCallback (D:\webDev\Secrets - Starting Code\node_modules\mongoose\lib\index.js:1135:10)
    at Mongoose.connect (D:\webDev\Secrets - Starting Code\node_modules\mongoose\lib\index.js:344:20)
    at Object.<anonymous> (D:\webDev\Secrets - Starting Code\app.js:30:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5604) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5604) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
MongooseError: Operation `users.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (D:\webDev\Secrets - Starting Code\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:184:20)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

**Comment by leonardlin** [comment]
@shruti9rk Agenda is not using mongoose.
Or how were you able to produce this error with mongoose
