### ISSUE TITLE
Agenda on 'sharded' cluster 

### ISSUE THREAD

**Issue by vinhphuctadang** [agenda/agenda#1093]
Currently, I am working with agenda for some scheduled task when I found an error when try to 'shard' the agendaJobs (my collection for saving scheduled jobs) based on data._id (because I think it is reasonable):
Here is the error:
When sharding the collection based on data._id, the ``job.unique()`` works fine, but when I wait for the scheduled task to be run, it won't. I come debug with 'debug==true' and see /find-and-lock-next-jobs.js, there is really an error shown that it cannot findOneAnUpdate without 'shardkey', details are:
```
agenda:internal:_findAndLockNextJob _findAndLockNextJob(My job, [Function]) +1s
agenda:internal:processJobs [My job] job lock failed while filling queue { MongoError: Query for sharded findAndModify must contain the shard key
    at MessageStream.messageHandler (/home/foo/projects/LedgarStorage/node_modules/agenda/node_modules/mongodb/lib/cmap/connection.js:261:20)
    at emitOne (events.js:116:13)
    at MessageStream.emit (events.js:211:7)
    at processIncomingData (/home/foo/projects/LedgarStorage/node_modules/agenda/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/home/foo/projects/LedgarStorage/node_modules/agenda/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at doWrite (_stream_writable.js:396:12)
    at writeOrBuffer (_stream_writable.js:382:5)
    at MessageStream.Writable.write (_stream_writable.js:290:11)
    at Socket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)
```
So, how could I made my collection agendaJobs efficiently sharded, get rid of this error? I may choose the field 'nextRunAt' as shard key ??

**Comment by vinhphuctadang** [comment]
I have decided to change "findOneAndUpdate" => "findOne" then updateOne, which will support mongo shards.
