### ISSUE TITLE
(node:3208) UnhandledPromiseRejectionWarning: ReferenceError: bot is not defined

### ISSUE THREAD

**Issue by Slavi473** [agenda/agenda#1284]
PS C:\Users\Admin\Desktop\Discord Bot> node .
This bot is online
(node:3208) UnhandledPromiseRejectionWarning: ReferenceError: bot is not defined
    at Client.<anonymous> (C:\Users\Admin\Desktop\Discord Bot\index.js:10:5)
    at Client.emit (events.js:315:20)
    at WebSocketManager.triggerClientReady (C:\Users\Admin\Desktop\Discord Bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:431:17)
    at WebSocketManager.checkShardsReady (C:\Users\Admin\Desktop\Discord Bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:415:10)
    at WebSocketShard.<anonymous> (C:\Users\Admin\Desktop\Discord Bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:197:14)
    at WebSocketShard.emit (events.js:315:20)
    at WebSocketShard.checkReady (C:\Users\Admin\Desktop\Discord Bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:475:12)
    at WebSocketShard.onPacket (C:\Users\Admin\Desktop\Discord Bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:447:16)
    at WebSocketShard.onMessage (C:\Users\Admin\Desktop\Discord Bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (C:\Users\Admin\Desktop\Discord Bot\node_modules\ws\lib\event-target.js:132:16)
(node:3208) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3208) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by koresar** [comment]
Looks like your bug is right in this file: `C:\Users\Admin\Desktop\Discord Bot\index.js:10:5`
As your stack trace shown.

Please, avoid bug reports without any explanation next time. Otherwise, we might get annoyed.
