### ISSUE TITLE
 TimeoutOverflowWarning: 2591699977 does not fit into a 32-bit signed integer.

### ISSUE THREAD

**Issue by erwanriou** [agenda/agenda#1305]
Hello,

observing this error in a container in kubernetes of the following configurations:
`node:15.0.1-alpine` where i am using the `"agenda": "4.1.3"`

Even after restarting/rollout the deployment the error keep popping after some time (few minutes). 
Launching with more detail indicate me that it is an agenda issue.

```
Error
2021-05-07 11:45:00.360 CEST(node:17) TimeoutOverflowWarning: 2578743081 does not fit into a 32-bit signed integer.
Error
2021-05-07 11:45:00.387 CESTTimeout duration was set to 1.
Error
2021-05-07 11:45:00.387 CEST at new Timeout (node:internal/timers:167:15)
Error
2021-05-07 11:45:00.387 CEST at setTimeout (node:timers:158:19)
Error
2021-05-07 11:45:00.387 CEST at jobProcessing (/app/node_modules/agenda/dist/utils/process-jobs.js:229:17)
Error
2021-05-07 11:45:00.387 CEST at /app/node_modules/agenda/dist/utils/process-jobs.js:194:25
Error
2021-05-07 11:45:00.387 CEST at Generator.next (<anonymous>)
Error
2021-05-07 11:45:00.387 CEST at fulfilled (/app/node_modules/agenda/dist/utils/process-jobs.js:5:58)
Error
2021-05-07 11:45:00.387 CEST at processTicksAndRejections (node:internal/process/task_queues:93:5)
```

i saw some issue last year about it but i though the changes was fixed and commited. Anyhow if you have an idea how i could fix it. Right now my only solution was to manually delete the collections of agendaJob in mongodb before restart the deployment.

As a side info, this happen after a cluster failure and a the recovery of it. It might have been some side effect memory leak or something.

**Comment by erwanriou** [comment]
i saw through other issues that it's seem that it's due to a 21 days limitation for jobs.

#If there are multiple job definitions, and you have lockLimit and maxConcurrency set, there are cases where jobs do not get picked up even though they should already be processed. The reason behind that is that they are "falsely" blocked by another job that gets a lot of attention (e.g. a lot of new jobs are queued). (see #1130)

Anyway, this could lead to that, that a job is in there for more than 21 days (which is the 32 unsigned int limit that setTimeout has) and would cause this issue.

I will try investigate in my own to see if i can found a turnaround regarding it. Does Agenda accept PRs ?

**Comment by hzlu** [comment]
I encounter the same issue
I use `job.processEvery('1 week', { skipImmediate: true })`
after the code run multi times, job's next run time will increase and raise warning
