### ISSUE TITLE
Tests Hangs on master

### ISSUE THREAD

**Issue by harisvsulaiman** [agenda/agenda#1369]
```bash

  find-and-lock-next-job
    1) "before each" hook for "should find jobs without lockedAt property"
    2) "after each" hook for "should find jobs without lockedAt property"


  74 passing (9s)
  2 failing

  1) find-and-lock-next-job
       "before each" hook for "should find jobs without lockedAt property":
     ReferenceError: jobs is not defined
      at Context.<anonymous> (test/find-and-lock-next-job.js:37:7)

  2) find-and-lock-next-job
       "after each" hook for "should find jobs without lockedAt property":
     TypeError: Cannot read property 'collection' of null
      at clearJobs (test/find-and-lock-next-job.js:18:18)
      at Context.<anonymous> (test/find-and-lock-next-job.js:52:11)
```

**Comment by harisvsulaiman** [comment]
cc @koresar @pdfowler

**Comment by koresar** [comment]
I've fixed the hang on master. The `mocha` needed the `--exit` flag. 
However, the current master branch contains one broken test. I couldn't fix it.
