### ISSUE TITLE
job.setShouldSaveResult is not a function

### ISSUE THREAD

**Issue by varungujarathi9** [agenda/agenda#1440]
Hi, I am getting the below error while using setShouldSaveResult method. 
```
(node:77334) UnhandledPromiseRejectionWarning: TypeError: job.setShouldSaveResult is not a function
    at trial (/home/<>/<>/later.js:25:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:77334) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:77334) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
For error replication purposes I have put the details below

**main.js**
```
const express = require('express')
const os = require('os')
const process = require('process')
const Agenda = require('agenda')

async function trial() {
  const agenda = new Agenda({
    db: { address: '<URL>', collection: 'scheduler' },
    name: `${os.hostname}-${process.pid}`,
  })
  await agenda.start();

  const startDate = new Date('2022-03-30');
  const endDate = new Date('2022-04-30');
  const time = '00:42:00'

  agenda.define('printAnalyticsReport', async (job) => {
    console.log('I print a report!');
  });

  const job = agenda.create('printAnalyticsReport', { userCount: 100 })

  await job.repeatEvery('1 day', { startDate, endDate, timezone: 'Asia/Kolkata' })
  await job.schedule(time)
  await job.setShouldSaveResult(true);
  await job.save()
}

trial()
const app = express()
const PORT = process.env.PORT || 8000
app.listen(PORT, () => {
  console.log('Started switchr-server on port:', PORT)
})
```
**agenda** dependency version is 4.2.1 in the package.json

After checking the dependency code in `node_modules` I could see that method is missing

**Comment by harisvsulaiman** [comment]
@varungujarathi9  Please update to the new release https://github.com/agenda/agenda/releases/tag/v4.3.0
