### ISSUE TITLE
mongodb 5.1.0 support

### ISSUE THREAD

**Issue by palmtown** [agenda/agenda#1525]
Hello Community,

Please add support for mongodb 5.1.0.  I have verified an issue as mentioned at https://github.com/agenda/agenda/issues.  Also, another issue was discovered as shown below.  By providing support for mongodb 5.1.0, both these issues would be resolved.

BSONVersionError: Unsupported BSON version, bson types must be from bson 5.0 or later
    at serializeInto (/agenda/node_modules/bson/lib/bson.cjs:3621:23)
    at serializeObject (/agenda/node_modules/bson/lib/bson.cjs:3183:22)
    at serializeInto (/agenda/node_modules/bson/lib/bson.cjs:3617:25)
    at Object.serialize (/agenda/node_modules/bson/lib/bson.cjs:3999:32)
    at Msg.serializeBson (/agenda/node_modules/mongodb/lib/cmap/commands.js:383:21)
    at Msg.makeDocumentSegment (/agenda/node_modules/mongodb/lib/cmap/commands.js:377:37)
    at Msg.toBin (/agenda/node_modules/mongodb/lib/cmap/commands.js:366:29)
    at MessageStream.writeCommand (/agenda/node_modules/mongodb/lib/cmap/message_stream.js:43:34)
    at write (/agenda/node_modules/mongodb/lib/cmap/connection.js:483:30)
    at Connection.command (/agenda/node_modules/mongodb/lib/cmap/connection.js:317:13)

**Comment by sebamarynissen** [comment]
See https://github.com/agenda/agenda/issues/1547.

**Comment by prasannawilliams** [comment]
See #1534

**Comment by saskysamonte** [comment]
See #1534
