### ISSUE TITLE
[Error] job lock failed while filling queue TypeError: Cannot read properties of null (reading 'value')

### ISSUE THREAD

**Issue by rkreienbuehl** [agenda/agenda#1587]
I get an Error for every job that is scheduled:
```sh
  agenda:internal:processJobs [worker] job lock failed while filling queue TypeError: Cannot read properties of null (reading 'value')
    at Agenda.<anonymous> (/Users/xyz/Projekte/node_modules/agenda/lib/agenda/find-and-lock-next-job.ts:67:14)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/xyz/Projekte/node_modules/agenda/dist/agenda/find-and-lock-next-job.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) +2ms
```

Agenda version: `5.0.0`
MongoDB version: `4.17.2`

**Comment by windward-hive** [comment]
@rkreienbuehl agenda is buggy and unmaintained. [use pulse](https://github.com/pulsecron/pulse)
