### ISSUE TITLE
TypeError: Cannot read property 'concurrency' of undefined - Local and remote mongo instances using mongoose on Ubuntu and OS X

### ISSUE THREAD

**Issue by karan** [agenda/agenda#163]
Connecting to a `mongolab.com` mongodb instance as shown in #156 by @lucasmonteverde. 

Stack trace:

```
worker-3 (out): 2015-03-28 23:42 -04:00: Database Connection Successfully Opened at mongodb://xxxxxxxxxxxxxx.mongolab.com:43971/heroku_appxxxxxx
worker-3 (err): 2015-03-28 23:42 -04:00: /var/www/Bumper/node_modules/mongoose/node_modules/mongodb/lib/utils.js:97
worker-3 (err):     process.nextTick(function() { throw err; });
worker-3 (err):                                         ^
worker-3 (err): TypeError: Cannot read property 'concurrency' of undefined
worker-3 (err):     at runOrRetry (/var/www/Bumper/node_modules/agenda/lib/agenda.js:387:26)
worker-3 (err):     at jobProcessing (/var/www/Bumper/node_modules/agenda/lib/agenda.js:380:7)
worker-3 (err):     at /var/www/Bumper/node_modules/agenda/lib/agenda.js:363:9
worker-3 (err):     at /var/www/Bumper/node_modules/agenda/lib/agenda.js:296:5
worker-3 (err):     at handleCallback (/var/www/Bumper/node_modules/mongoose/node_modules/mongodb/lib/utils.js:95:12)
worker-3 (err):     at /var/www/Bumper/node_modules/mongoose/node_modules/mongodb/lib/collection.js:1400:14
worker-3 (err):     at handleCallback (/var/www/Bumper/node_modules/mongoose/node_modules/mongodb/lib/utils.js:95:12)
worker-3 (err):     at /var/www/Bumper/node_modules/mongoose/node_modules/mongodb/lib/db.js:247:5
worker-3 (err):     at /var/www/Bumper/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:770:13
worker-3 (err):     at Callbacks.emit (/var/www/Bumper/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:84:3)
```

**Comment by karan** [comment]
Also doesn't work for a local `mongod` instance. Anyone has any ideas how to debug this issue?

**Comment by karan** [comment]
`worker.js`

```js
var Agenda = require('agenda');

var agenda = new Agenda();

var jobs = require('mongoose').connection.collection('jobs');

jobs.ensureIndex({
    nextRunAt: 1,
    lockedAt: 1,
    name: 1,
    priority: 1
}, function() {});

agenda.mongo(jobs);


var jobTypes = ['job1', 'job2'];

jobTypes.forEach(function(type) {
  require('./jobs/' + type)(agenda);
})

if(jobTypes.length) {
  agenda.start();
}

function graceful() {
  console.log('Stopping agenda');
  agenda.stop(function() {
    process.exit(0);
  });
}

process.on('SIGTERM', graceful);
process.on('SIGINT' , graceful);

module.exports = agenda;

```

**Comment by karan** [comment]
One of the jobs:

```js
module.exports = function(agenda) {

  agenda.define('send request confirmation text', function(job, done) {
    console.log('SEND TEXT: ' + JSON.stringify(job.attrs.data));
    // do a bunch of other stuff and call `done()`
  });

}
```

**Comment by omakoleg** [comment]
I have smt like that, You just don have `agenda.define` before doing agenda.schedule, so it could not find  job configuration block (in our case undefined) so `Cannot read property 'concurrency' of undefined` came from here.
Could be:
- I see one extra symbol `'` in definition
- I dont see `send request confirmation text` in you loaded, in variable `jobTypes `

**Comment by karan** [comment]
1. Typo, fixed it
2. The loader is for the js file that holds the definition. Everything is there!

> You just dont have agenda.define before doing agenda.schedule, so it could not find job configuration block

I use this code to schedule jobs:

```js
var agenda = require('./../worker');
agenda.schedule(....)
```

**Comment by inetfuture** [comment]
Any updates? I run into the same problem after upgrading mongoose to 4.x

Seems this query in `node_modules/agenda/lib/agenda.js` return wrong result:

```js
this._db.findAndModify(
    {
      nextRunAt: {$lte: this._nextScanAt},
      disabled: { $ne: true },
      $or: [
        {lockedAt: null},
        {lockedAt: {$exists: false}},
        {lockedAt: {$lte: lockDeadline}}
      ],
      name: jobName
    },
    {'priority': -1},
    {$set: {lockedAt: now}},
    {'new': true},
    findJobsResultWrapper(this, cb)
  );

function findJobsResultWrapper(agenda, cb) {
  return function (err, jobs) {
    console.log('lllllllllll', err, jobs);
    if (jobs) {
      //query result can be array or one record
      if (Array.isArray(jobs)) {
        jobs = jobs.map(createJob.bind(null, agenda));
      } else {
        jobs = createJob(agenda, jobs);
      }
    }

    cb(err, jobs);
  };
}
```

The console output is `lllllllllll null { value: null, ok: 1 }`

**Comment by inetfuture** [comment]
The mongoose 4.x uses the latest mongodb driver 2.x

**Comment by inetfuture** [comment]
A non-null result looks like this:

```
lllllllllll null { lastErrorObject: 
   { connectionId: 14282,
     updatedExisting: true,
     n: 1,
     syncMillis: 0,
     writtenTo: null,
     err: null,
     ok: 1 },
  value: 
   { _id: 5552fb12f3256c9946aeabb8,
     type: 'single',
     data: null,
     priority: 0,
     nextRunAt: Wed May 13 2015 15:43:00 GMT+0800 (CST),
     repeatInterval: '*/1 * * * *',
     lastModifiedBy: 'aaronm.s1.46338',
     lockedAt: Wed May 13 2015 15:43:20 GMT+0800 (CST) },
  ok: 1 }
```

So the cause is mongodb driver's breaking change

**Comment by barrtender** [comment]
I got this error if I tried to schedule a job that I hadn't defined yet. I changed the name of my job in the definition but forgot to change it in one place when I scheduled it and got this error. Maybe check your spellings in the places you schedule it.

**Comment by melvin15may** [comment]
@barrtender Thank you. Had the exact same problem. Wrong spelling.

**Comment by jakeorr** [comment]
@karan did you find a solution to this? I'm running into the same issue.

**Comment by derekstavis** [comment]
I have the exact same issue. My code block looks like this:

```javascript
  var Agenda = require('agenda')
    , sync = require('./sync');

  function schedule() {
    return new Promise(function (resolve, reject) {
      var agenda = new Agenda({db: {address: 'mongodb://localhost/agenda'}});
      agenda.define('sync system', sync.execute);

      agenda.on('error', reject);
      agenda.on('ready', function() {
        agenda.schedule('sync system', 'this morning at 12:00am');
        agenda.start();
        resolve();
      });
    });
  }
```

**Comment by simison** [comment]
Since this issue Mongo driver has been upgraded to `^2.2`, would be interesting to hear if that solved this.

Anyways since there is no activity here since 2015, I'll close. Feel free to comment if it's still relevant and we'll open this again.
