### ISSUE TITLE
Unable to run sample

### ISSUE THREAD

**Issue by teledna** [agenda/agenda#229]
I am getting the following error 
"Cannot call method 'findOneAndUpdate' of undefined"
I have followed this blog to run sample
http://www.robinwieruch.de/node-js-scheduling-periodic-tasks-with-agenda/

**Comment by MooXo** [comment]
Same issue here

```
var agenda = new Agenda({db: {address: "mongodb://********@****.mongolab.com:60478/*******"}});

agenda.define('write console', function(job){
  console.log("Job %s executed", job.attrs.name);
});

agenda.every('15 minutes', 'write console');

agenda.on('ready', function(){
  console.log('Agenda connected to mongodb');
  agenda.start();
});
```

when executed cause:

```
MacBook-Pro-uzivatela-Viktor:vicinityServer viktor$ DEBUG=vicinityServer:* npm start

> vicinityServer@0.0.0 start /Users/viktor/WebstormProjects/vicinity/vicinityServer
> node ./bin/www

Moment Timezone 0.3.1 was already loaded with data from 2015a
/Users/viktor/WebstormProjects/vicinity/vicinityServer/node_modules/agenda/lib/agenda.js:341
    this._collection.findAndModify({name: props.name, type: 'single'}, {}, update, {upsert: true, new: true}, processDbResult);
                    ^

TypeError: Cannot read property 'findAndModify' of undefined
    at Agenda.saveJob (/Users/viktor/WebstormProjects/vicinity/vicinityServer/node_modules/agenda/lib/agenda.js:341:21)
    at Job.save (/Users/viktor/WebstormProjects/vicinity/vicinityServer/node_modules/agenda/lib/job.js:232:15)
    at createJob (/Users/viktor/WebstormProjects/vicinity/vicinityServer/node_modules/agenda/lib/agenda.js:221:9)
    at Agenda.every (/Users/viktor/WebstormProjects/vicinity/vicinityServer/node_modules/agenda/lib/agenda.js:211:12)
    at Object.<anonymous> (/Users/viktor/WebstormProjects/vicinity/vicinityServer/app.js:19:8)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.1
npm ERR! npm  v3.3.9
npm ERR! code ELIFECYCLE

```
package.json:

```
{
  "name": "vicinityServer",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "node ./bin/www"
  },
  "dependencies": {
    "agenda": "^0.8.0",
    "agendash": "^0.3.1",
    "body-parser": "~1.13.2",
    "cookie-parser": "~1.3.5",
    "debug": "~2.2.0",
    "express": "~4.13.1",
    "jade": "~1.11.0",
    "morgan": "~1.6.1",
    "serve-favicon": "~2.3.0"
  }
}

```

**Comment by MooXo** [comment]
IMHO this will not work. NodeJS is event based. 

This examples tries to writing job in database, however database is not initialized yet.

As in README:
```

agenda.define('delete old users', function(job, done) {
  User.remove({lastLogIn: { $lt: twoDaysAgo }}, done);
});

agenda.on('ready', function() {
  agenda.every('3 minutes', 'delete old users');

  // Alternatively, you could also do:
  agenda.every('*/3 * * * *', 'delete old users');

  agenda.start();
});
```

Scheduling job should be done after 'ready' event is received.
