### ISSUE TITLE
MongoError: no mongos proxy available

### ISSUE THREAD

**Issue by ricalhsieh** [agenda/agenda#372]
I'm using mongos and had error:

/usr/src/app/node_modules/mongodb/lib/utils.js:98
    process.nextTick(function() { throw err; });
                                  ^
MongoError: no mongos proxy available
    at State.pickServer (/usr/src/app/node_modules/mongodb-core/lib/topologies/mongos.js:268:33)
    at Mongos.command (/usr/src/app/node_modules/mongodb-core/lib/topologies/mongos.js:713:33)
    at Mongos.command (/usr/src/app/node_modules/mongodb/lib/mongos.js:355:17)
    at executeCommand (/usr/src/app/node_modules/mongodb/lib/db.js:305:19)
    at Db.command (/usr/src/app/node_modules/mongodb/lib/db.js:329:44)
    at findAndModify (/usr/src/app/node_modules/mongodb/lib/collection.js:2387:13)
    at Collection.findAndModify (/usr/src/app/node_modules/mongodb/lib/collection.js:2325:44)
    at Agenda._findAndLockNextJob (/usr/src/app/node_modules/agenda/lib/agenda.js:429:22)
    at jobQueueFilling (/usr/src/app/node_modules/agenda/lib/agenda.js:607:10)
    at processJobs (/usr/src/app/node_modules/agenda/lib/agenda.js:485:7)
    at Timeout.wrapper [as _onTimeout](timers.js:421:11)
    at tryOnTimeout (timers.js:228:11)
    at Timer.listOnTimeout (timers.js:202:5)

Checking the relative issue, it could be like [this](https://github.com/Automattic/mongoose/issues/3945).
Upgrade mongodb driver to 2.1.13 or 2.1.14 could solve this issue.

From (#368), the source code were updated but when I install from npm, it still uses version 2.1.11.
Would be great if can help to update npm.

**Comment by simison** [comment]
Mongo driver is now updated to `^2.2` and finally version [0.9.1](https://github.com/agenda/agenda/blob/master/History.md#091--2017-03-22) should have this via npm as well.
