### ISSUE TITLE
TypeError: Cannot read property 'insertOne' of undefined

### ISSUE THREAD

**Issue by Febby315** [agenda/agenda#420]
var job = agenda.create('printAnalyticsReport', {userCount: 100});
job.save(function(err) {
    console.log("Job successfully saved");
});
//

ERROR：
TypeError: Cannot read property 'insertOne' of undefined
    at Agenda.saveJob (D:\Workspaces\Nodejs\AendaTest\node_modules\agenda\lib\agenda.js:364:21)
    at Job.save (D:\Workspaces\Nodejs\AendaTest\node_modules\agenda\lib\job.js:233:15)
    at Object.<anonymous> (D:\Workspaces\Nodejs\AendaTest\app.js:18:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)

**Comment by cylim** [comment]
This might be related to #213

**Comment by Febby315** [comment]
@cylim 谢谢，因为我没有把jab.save()放在ready事件处理函数中。Thank you, because I didn't put jab.save() in the ready event handler.
