### ISSUE TITLE
Getting RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by mystery-man** [agenda/agenda#477]
Once in a week iam getting this error and because of that my server gets crashed. Iam scheduling over 2m jobs daily.

RangeError: Maximum call stack size exceeded
    at jobProcessing (D:\home\site\wwwroot\node_modules\agenda\lib\agenda.js:641:31)
    at runOrRetry (D:\home\site\wwwroot\node_modules\agenda\lib\agenda.js:658:13)
    at jobProcessing (D:\home\site\wwwroot\node_modules\agenda\lib\agenda.js:642:7)
    at runOrRetry (D:\home\site\wwwroot\node_modules\agenda\lib\agenda.js:658:13)
    at jobProcessing (D:\home\site\wwwroot\node_modules\agenda\lib\agenda.js:642:7)
    at runOrRetry (D:\home\site\wwwroot\node_modules\agenda\lib\agenda.js:658:13)
    at jobProcessing (D:\home\site\wwwroot\node_modules\agenda\lib\agenda.js:642:7)
    at runOrRetry (D:\home\site\wwwroot\node_modules\agenda\lib\agenda.js:658:13)
    at jobProcessing (D:\home\site\wwwroot\node_modules\agenda\lib\agenda.js:642:7)
    at runOrRetry (D:\home\site\wwwroot\node_modules\agenda\lib\agenda.js:658:13)
    at jobProcessing (D:\home\site\wwwroot\node_modules\agenda\lib\agenda.js:642:7)
    at runOrRetry (D:\home\site\wwwroot\node_modules\agenda\lib\agenda.js:658:13)
    at jobProcessing (D:\home\site\wwwroot\node_modules\agenda\lib\agenda.js:642:7)
    at runOrRetry (D:\home\site\wwwroot\node_modules\agenda\lib\agenda.js:658:13)
    at jobProcessing (D:\home\site\wwwroot\node_modules\agenda\lib\agenda.js:642:7)
    at runOrRetry (D:\home\site\wwwroot\node_modules\agenda\lib\agenda.js:658:13)

It seems that these methods are running recursively which is the issue here.

**Comment by michelem09** [comment]
What are you passing as data for jobs? For example you can't pass a MongoDB document you need to convert it to a simple object (`toObject()`).
Did you look at this? https://github.com/agenda/agenda/issues/182

**Comment by mystery-man** [comment]
Yes, I've checked out that issue and I am passing a simple object.
Something like this => {id : scheduledData._id.toString()}

**Comment by emhagman** [comment]
Wouldn't this be inevitable? You said you have 2,000,000 jobs a day? If the number of jobs exceeds the NodeJS stack size and we don't use any `setTimeout` or `setImmediate`, etc, this certainly can occur since processJobs() essentially calls it self all the time.

`node --v8-options | grep -B0 -A1 stack_size`

The default is `984kB` for the V8 engine in NodeJS. Can you try running it with:
`node --stack_size=2000 server.js` or something even higher than that on your Agenda worker?

It might be a good idea to run one of the internal `processJobs()` here using`setTimeout` or `setImmediate` on the following lines although I don't know how this would affect locking, etc.

https://github.com/agenda/agenda/blob/master/lib/agenda.js#L940
or here:
https://github.com/agenda/agenda/blob/master/lib/agenda.js#L952

**Comment by mystery-man** [comment]
That is correct @emhagman. I thought about adding the setTimeout in calling processJobs as that would close the stack. But as you mentioned iam not sure how that would affect other stuffs i.e locking, priority etc.

As for the stack size I've heard that it's not the right approach as we can increase the size but it also depends on the OS with respect to the memory.

**Comment by emhagman** [comment]
@mystery-man It is certainly isn't the right approach, I wanted to see if that fixes the problem to assure myself that was the problem. I will try and see what happens locally with that code change and run some tests.

**Comment by mystery-man** [comment]
That would be really helpful @emhagman . Thanks for that :)

**Comment by emhagman** [comment]
@mystery-man Do you have a test environment where you would be willing to give this a go? All tests are passing with the change.

You can simply put: `"agenda": "draftedus/docket#process-job-set-immediate"` in your `package.json`. I don't have 2M jobs in an environment to test over a long period of time.

I am fairly confident this should not affect anything considering the tests pass and the nature of `jobProcessing()` is such that it can be called at anytime and in fact, is still being called separately within `setInterval()` at the process time specified.

Essentially, I keep track of the number of times `jobProcessing()` is called and break it out into `setImmediate()` after every 100 calls within itself.

**Comment by mystery-man** [comment]
I dont have a test environment currently...
Let me try and replicate that and will get back to you.

Are you going to do this now ?
`Essentially, I keep track of the number of times jobProcessing() is called and break it out into setImmediate() after every 100 calls within itself.`

**Comment by emhagman** [comment]
Sorry I wasn't clear enough! It's already done:
https://github.com/draftedus/docket/tree/process-job-set-immediate

That's what I was referring to about changing your `package.json`

**Comment by mystery-man** [comment]
Oh i  get it.
I will test it out and will get back to you.
Thanks for all this 👍

**Comment by emhagman** [comment]
Of course, let me know how it goes!

**Comment by emhagman** [comment]
@mystery-man Any luck?

**Comment by mystery-man** [comment]
@emhagman I've tested it out and deployed on production 2 days back. So far it's working great. :)

**Comment by mystery-man** [comment]
@emhagman Just for the sake of confirmation. The new logic is working fine but I am getting messages from customers that the job is running multiple times for them. Can this be related to the changed logic because earlier I didn't have this issue ?

The production environment is running multiple instances. Can the new interval along with multiple instances cause this issue ?
