### ISSUE TITLE
Auto reconnect Mongodb not working

### ISSUE THREAD

**Issue by arthursp** [agenda/agenda#564]
"Agenda is configured by default to automatically reconnect indefinitely, emitting an error event when no connection is available on each process tick, allowing you to restore the Mongo instance without having to restart the application."

I had this : 

```bash
13/12/2017 21:02:00
13/12/2017 21:02:00/usr/src/app/node_modules/mongodb/lib/utils.js:123
13/12/2017 21:02:00    process.nextTick(function() { throw err; });
13/12/2017 21:02:00                                  ^
13/12/2017 21:02:00Error: read ECONNRESET
13/12/2017 21:02:00    at _errnoException (util.js:1026:11)
13/12/2017 21:02:00    at TCP.onread (net.js:606:25)
13/12/2017 21:02:00npm info lifecycle scheduler@1.0.0~start: Failed to exec start script
13/12/2017 21:02:00npm ERR! code ELIFECYCLE
13/12/2017 21:02:00npm ERR! errno 1
13/12/2017 21:02:00npm ERR! scheduler@1.0.0 start: `node index.js`
13/12/2017 21:02:00npm ERR! Exit status 1
13/12/2017 21:02:00npm ERR!
13/12/2017 21:02:00npm ERR! Failed at the scheduler@1.0.0 start script.
13/12/2017 21:02:00npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
13/12/2017 21:02:00
13/12/2017 21:02:00npm ERR! A complete log of this run can be found in:
13/12/2017 21:02:00npm ERR!     /root/.npm/_logs/2017-12-13T20_02_00_317Z-debug.log
```

And It don't try to reconnect automaticaly.

The way I connect to mongodb: 

```javascript
var mongoConnectionString = 'mongodb://'+process.env.MONGOUSER+':'+process.env.MONGOPASSWORD+'@mongodb/agendash';

var agenda = new Agenda({
  db: {address: mongoConnectionString},
  collection: 'agendaJobs'
})
```

**Comment by simllll** [comment]
I have a similar issue:

```
[ERROR] Error: MongoDB connection is not recoverable, application restart required
    at Agenda.module.exports [as _findAndLockNextJob] (/var/node_modules/agenda/lib/agenda/find-and-lock-next-job.js:34:10)
    at jobQueueFilling (/var/node_modules/agenda/lib/utils/process-jobs.js:200:10)
    at Agenda.module.exports (/var/node_modules/agenda/lib/utils/process-jobs.js:32:9)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)

```

Shouldn't it back off and retry, like "mongoose" does in my case.

thanks
Simon

**Comment by Getitdan** [comment]
Please help. My process is crushing a lot because of Agenda. Any connection drop causes it to exit.

**Comment by arthursp** [comment]
`25/04/2018 01:12:36/usr/src/app/node_modules/mongodb/lib/utils.js:123
25/04/2018 01:12:36    process.nextTick(function() { throw err; });
25/04/2018 01:12:36                                  ^
25/04/2018 01:12:36MongoError: can't connect to new replica set master [...], err: couldn't connect to server ...:27017, connection attempt failed
25/04/2018 01:12:36    at Function.MongoError.create (/usr/src/app/node_modules/mongodb-core/lib/error.js:31:11)
25/04/2018 01:12:36    at /usr/src/app/node_modules/mongodb-core/lib/connection/pool.js:497:72
25/04/2018 01:12:36    at authenticateStragglers (/usr/src/app/node_modules/mongodb-core/lib/connection/pool.js:443:16)
25/04/2018 01:12:36    at Connection.messageHandler (/usr/src/app/node_modules/mongodb-core/lib/connection/pool.js:477:5)
25/04/2018 01:12:36    at Socket.<anonymous> (/usr/src/app/node_modules/mongodb-core/lib/connection/connection.js:333:22)
25/04/2018 01:12:36    at emitOne (events.js:115:13)
25/04/2018 01:12:36    at Socket.emit (events.js:210:7)
25/04/2018 01:12:36    at addChunk (_stream_readable.js:266:12)
25/04/2018 01:12:36    at readableAddChunk (_stream_readable.js:253:11)
25/04/2018 01:12:36    at Socket.Readable.push (_stream_readable.js:211:10)
25/04/2018 01:12:36npm info lifecycle scheduler@1.0.0~start: Failed to exec start script
25/04/2018 01:12:36npm ERR! code ELIFECYCLE
25/04/2018 01:12:36npm ERR! errno 1
25/04/2018 01:12:36npm ERR! scheduler@1.0.0 start: `node index.js`
25/04/2018 01:12:36npm ERR! Exit status 1
25/04/2018 01:12:36npm ERR!
25/04/2018 01:12:36npm ERR! Failed at the scheduler@1.0.0 start script.
25/04/2018 01:12:36npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by cncolder** [comment]
Before pr. You should fix with hammer:

```js
const agenda = new Agenda().mongo(/* existed mongo connection */ conn)

process.on('uncaughtException', err => {
    if (err.message === 'MongoDB connection is not recoverable, application restart required') {
        agenda.stop(() => console.log('agenda stop'))
    } else {
        process.exit(1)
    }
})

conn.on('reconnected', () => {
    console.log('agenda restart')
    agenda.start()
})
```

**Comment by iocast** [comment]
I have it too
```
/node_modules/agenda/lib/utils/process-jobs.js:203
        throw err;
        ^

Error: MongoDB connection is not recoverable, application restart required
    at Agenda.module.exports [as _findAndLockNextJob] (/node_modules/agenda/lib/agenda/find-and-lock-next-job.js:34:10)
    at jobQueueFilling (/node_modules/agenda/lib/utils/process-jobs.js:200:10)
    at Agenda.module.exports (/node_modules/agenda/lib/utils/process-jobs.js:32:9)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

any solution?

**Comment by Dartv** [comment]
Same here

**Comment by wereldbolt** [comment]
Same issue here.

**Comment by ScripterSugar** [comment]
Same issue here. Any fix?

**Comment by theohogberg** [comment]
try updating agenda to 3.1.0 this solved the issue for me
