### ISSUE TITLE
Agenda.purge is broken

### ISSUE THREAD

**Issue by rtwalz** [agenda/agenda#606]
Running agenda.purge produces this error
```
/Users/riley/Desktop/aud/node_modules/agenda/lib/agenda/cancel.js:13
  this._collection.deleteMany(query, (error, result) => {
                   ^

TypeError: Cannot read property 'deleteMany' of undefined
    at Agenda.module.exports [as cancel] (/Users/riley/Desktop/aud/node_modules/agenda/lib/agenda/cancel.js:13:20)
    at Agenda.module.exports [as purge] (/Users/riley/Desktop/aud/node_modules/agenda/lib/agenda/purge.js:13:8)
    at Object.<anonymous> (/Users/riley/Desktop/aud/index.js:584:8)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
```

**Comment by wingsbob** [comment]
@rtwalz Could you provide a code sample? At first glance this looks like `purge` has been called on an agenda instance before the connection has been completed.
