### ISSUE TITLE
Can't connect Agenda with MongoDB Atlas

### ISSUE THREAD

**Issue by jayakumarp** [agenda/agenda#673]
Seems like agenda appending "mongodb://". So, We could not connect agenda with MongoDB atlas. 

FYI:
lib -> agenda -> database.js

const self = this;
  if (!url.match(/^mongodb:\/\/.*/)) {
    url = 'mongodb://' + url;
  }

But the atlas connection string will be like
mongodb+srv://<username>:<password>@<mongo-cluster-url>/<database_name>

Please find the error below:

{ MongoError: Unescaped slash in userinfo section
    at parseConnectionString (/media/myname/DATA11/backup/Projects/myapp/code/apiserver/node_modules/agenda/node_modules/mongodb-core/lib/uri_parser.js:235:21)
    at connect (/media/myname/DATA11/backup/Projects/myapp/code/apiserver/node_modules/agenda/node_modules/mongodb/lib/operations/mongo_client_ops.js:179:3)
    at connectOp (/media/myname/DATA11/backup/Projects/myapp/code/apiserver/node_modules/agenda/node_modules/mongodb/lib/operations/mongo_client_ops.js:283:3)
    at executeOperation (/media/myname/DATA11/backup/Projects/myapp/code/apiserver/node_modules/agenda/node_modules/mongodb/lib/utils.js:420:24)
    at MongoClient.connect (/media/myname/DATA11/backup/Projects/myapp/code/apiserver/node_modules/agenda/node_modules/mongodb/lib/mongo_client.js:168:10)
    at Function.MongoClient.connect (/media/myname/DATA11/backup/Projects/myapp/code/apiserver/node_modules/agenda/node_modules/mongodb/lib/mongo_client.js:371:22)
    at Agenda.module.exports [as database] (/media/myname/DATA11/backup/Projects/myapp/code/apiserver/node_modules/agenda/lib/agenda/database.js:31:15)
    at Agenda (/media/myname/DATA11/backup/Projects/myapp/code/apiserver/node_modules/agenda/lib/agenda/index.js:56:12)
    at run (/media/myname/DATA11/backup/Projects/myapp/code/apiserver/agenda.js:14:16)
    at Object.<anonymous> (/media/myname/DATA11/backup/Projects/myapp/code/apiserver/agenda.js:36:1)
  name: 'MongoParseError',
  message: 'Unescaped slash in userinfo section',
  [Symbol(mongoErrorContextSymbol)]: {} }

**Comment by Tom5om** [comment]
I created a PR here: https://github.com/agenda/agenda/pull/674

That should solve your problam as well

**Comment by essuraj** [comment]
you can also use the legacy url to connect to atlas... but the modern one should be supported

**Comment by fega** [comment]
I'd say that Agenda shouldn't be validating the mongodb address, that's the job of the mongodb Driver

**Comment by Tom5om** [comment]
Yeah, not validating, it is a helper to say if you didn't put in the mongo:// it will add it for you, but you are right I dont think it should be part of it

**Comment by blake59** [comment]
Is there an update on this issue?

**Comment by Tom5om** [comment]
Hey Blake, yes I sent a pr, you can use my fork, but I need to send in some tests before it will be merged in. For now you could use the fork?

**Comment by simison** [comment]
Fixed in Agenda v2.0.2

**Comment by DavyCode** [comment]
@jayakumarp How did you resolve this issue? so i had a slash in the userinfo (user password) for my Mongo URI, removing it helped me resolve the problem. Not sure when this change took effect because i have the same userinfo working for other projects.

**Comment by jonathangaldino** [comment]
> @jayakumarp How did you resolve this issue? so i had a slash in the userinfo (user password) for my Mongo URI, removing it helped me resolve the problem. Not sure when this change took effect because i have the same userinfo working for other projects.

I fixed using the options object.

```js
new Agenda({
      db: {
        address: 'mongodb+srv://<user>:<password@server.mongodb.net/database?retryWrites=true&w=majority',
        options: { useNewUrlParser: true }
      }
    });
  }
```
