### ISSUE TITLE
Agenda get a job query return null

### ISSUE THREAD

**Issue by Yogendra0Sharma** [agenda/agenda#713]
Hello All
I have a small app using agenda.

the agenda.jobs() method return null but the job is successfully created in MongoDB.

code:- 

```
var Agenda = require('agenda');
var agenda = new Agenda({
		name: 'LightController',
		defaultLockLifetime: 5000,
		db: {
			address:'localhost:27017/agendaTestBaba',
			collection: "agendaJobs",
			options: {
				auto_reconnect: true,
				useNewUrlParser: true
			}
		},
		maxConcurrency: 200
	});
	agenda.processEvery('1 minutes');
	
	agenda.define('onOff', function (job, done) {
        console.log(job.attrs.data);
        done();
    });
	
	agenda.on('ready', function (err, job) {
		agenda.start();
		agenda.every('1 seconds','onOff');
		agenda.jobs({name:'onOff'}, function (err, j) {
			console.log(err);
			console.log(j);
		});
	});
```
Agenda :- "agenda": "^2.0.2"
Mongo:- db version v3.6.3 	

Do I need to always use the ready event in order to get jobs?

```
agenda.on('ready', function (err, job) {
		agenda.jobs({name:'onOff'}, function (err, j) {
			console.log(err);
			console.log(j);
		});
	});
```
or can i use the find query out side the ready block once the agenda is ready and running.

```
agenda.on('ready', function (err, job) {
		agenda.start?()
	});
agenda.jobs({name:'onOff'}, function (err, j) {
			console.log(err);
			console.log(j);
});
```
When i use agenda.jobs() outside the ready event then got follwing error:-

```
(node:10504) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'find' of undefined
    at Agenda.module.exports [as jobs] (C:\Users\10605\Desktop\NodeInterview\agendaWork\node_modules\agenda\lib\agenda\jobs.js:12:41)
    at Object.<anonymous> (C:\Users\10605\Desktop\NodeInterview\agendaWork\app.js:27:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

**Comment by alihesari** [comment]
@Yogendra0Sharma Hello, How did you solve your problem?
