### ISSUE TITLE
Update the documentation for callbacks

### ISSUE THREAD

**Issue by nemozny** [agenda/agenda#730]
Hi, in the documentation you still have agenda.cancel as a callback, but that is not true. My script got frozen on agenda.cancel, because it is already reimplemented as async/await. I had to look to your tests to find out.

**Comment by nemozny** [comment]
Same situation with job.save()
Please review all callback functions.

`unhandledRejection Error: This function does not accept a callback function. 1/0
    at module.exports (C:\Users\pavel.helia\Documents\NetBeansProjects\js\node_modules\agenda\lib\no-callback.js:12:11)
    at Job.module.exports [as save] (C:\Users\pavel.helia\Documents\NetBeansProjects\js\node_modules\agenda\lib\job\save.js:12:3)`

**Comment by j1348** [comment]
I am getting this kind of error while I rerun a job from agendash.

The immediat run has been working nevertheless.
```
Error: This function does not accept a callback function. 1/0
    at module.exports (.../app/node_modules/agenda/lib/no-callback.js:12:11)
    at Job.module.exports [as save] (.../app/node_modules/agenda/lib/job/save.js:12:3)
    at .../app/node_modules/agendash/lib/agendash.js:65:12
    at .../app/node_modules/agendash/node_modules/async/lib/async.js:718:13
    at iterate (.../app/node_modules/agendash/node_modules/async/lib/async.js:262:13)
    at async.forEachOfSeries.async.eachOfSeries (.../app/node_modules/agendash/node_modules/async/lib/async.js:281:9)
    at _parallel (.../app/node_modules/agendash/node_modules/async/lib/async.js:717:9)
    at Object.async.series (.../app/node_modules/agendash/node_modules/async/lib/async.js:739:9)
    at .../app/node_modules/agendash/lib/agendash.js:63:15
    at result (.../app/node_modules/agenda/node_modules/mongodb/lib/utils.js:414:17)
    at executeCallback (.../app/node_modules/agenda/node_modules/mongodb/lib/utils.js:406:9)
    at handleCallback (.../app/node_modules/agenda/node_modules/mongodb/lib/utils.js:128:55)
    at cursor.close (.../app/node_modules/agenda/node_modules/mongodb/lib/operations/cursor_ops.js:224:62)
    at handleCallback (.../app/node_modules/agenda/node_modules/mongodb/lib/utils.js:128:55)
    at completeClose (.../app/node_modules/agenda/node_modules/mongodb/lib/cursor.js:893:14)
    at _endSession (.../app/node_modules/agenda/node_modules/mongodb/lib/cursor.js:904:37)
    at Cursor._endSession (.../app/node_modules/agenda/node_modules/mongodb-core/lib/cursor.js:195:5)
    at Cursor._endSession (.../app/node_modules/agenda/node_modules/mongodb/lib/cursor.js:226:59)
    at Cursor.close (.../app/node_modules/agenda/node_modules/mongodb/lib/cursor.js:904:19)
    at cursor._next (.../app/node_modules/agenda/node_modules/mongodb/lib/operations/cursor_ops.js:224:23)
    at handleCallback (.../app/node_modules/agenda/node_modules/mongodb-core/lib/cursor.js:204:5)
    at _setCursorNotifiedImpl (.../app/node_modules/agenda/node_modules/mongodb-core/lib/cursor.js:433:38)
error Command failed with exit code 1.
```

Is the  `agendash@0.4.0` compatible with `agenda@2.0.2`?
