### ISSUE TITLE
TypeError: Cannot read property '_processInterval' of undefined

### ISSUE THREAD

**Issue by hasezoey** [agenda/agenda#804]
(using TypeScript 3.4.4)
- Agenda version: 2.0.2
- Node Version: 11.14.0
- Environment: Linux (Mint 19, agenda executed in Docker-alpine with nodemon)
- Small description of what happened:
when trying todo `await agenda.stop()` this comes up always
(while doing before & after initializing (`agenda.start())`)

- Any relevant stack track
```
TypeError: Cannot read property '_processInterval' of undefined
    at module.exports (/app/node_modules/agenda/lib/agenda/stop.js:41:22)
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/app/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:443:21)
```
- Agenda logs
```
Connecting to mongoose
Mongoose Connected!
2019-04-24T22:10:23.715Z agenda:db_init init database collection using name [jobs]
2019-04-24T22:10:23.716Z agenda:db_init attempting index creation
2019-04-24T22:10:23.716Z agenda:name Agenda.name(abab8f5e4ace - PID 17)
2019-04-24T22:10:23.717Z agenda:define job [deleteme] defined with following options: 
{ fn: [Function],
  concurrency: 5,
  lockLimit: 0,
  priority: 0,
  lockLifetime: 10000,
  running: 0,
  locked: 0 }
2019-04-24T22:10:23.717Z agenda:every Agenda.every(180000, 'deleteme', undefined)
2019-04-24T22:10:23.717Z agenda:create Agenda.create(deleteme, [Object])
2019-04-24T22:10:23.717Z agenda:job [deleteme:undefined] computing next run via interval [180000]
2019-04-24T22:10:23.718Z agenda:saveJob attempting to save a job into Agenda instance
2019-04-24T22:10:23.718Z agenda:saveJob [job undefined] set job props: 
{ name: 'deleteme',
  data: undefined,
  type: 'single',
  priority: 0,
  nextRunAt: 2019-04-24T22:10:23.717Z,
  repeatInterval: 180000,
  repeatTimezone: null,
  lastModifiedBy: 'abab8f5e4ace - PID 17' }
2019-04-24T22:10:23.718Z agenda:saveJob current time stored as 2019-04-24T22:10:23.718Z
2019-04-24T22:10:23.718Z agenda:saveJob job with type of "single" found
2019-04-24T22:10:23.718Z agenda:saveJob job has a scheduled nextRunAt time, protecting that field from upsert
2019-04-24T22:10:23.718Z agenda:saveJob calling findOneAndUpdate() with job name and type of "single" as query
2019-04-24T22:10:23.730Z agenda:db_init index creation success
2019-04-24T22:10:23.730Z agenda:start Agenda.start called, creating interval to call processJobs every [120000ms]
2019-04-24T22:10:23.731Z agenda:internal:processJobs starting to process jobs
2019-04-24T22:10:23.731Z agenda:internal:processJobs queuing up job to process: [deleteme]
2019-04-24T22:10:23.731Z agenda:internal:processJobs job [deleteme] lock status: shouldLock = true
2019-04-24T22:10:23.731Z agenda:internal:_findAndLockNextJob _findAndLockNextJob(deleteme, [Function], cb)
Agenda Started!
Express Started!
2019-04-24T22:10:23.736Z agenda:saveJob processDbResult() called with success, checking whether to process job immediately or not
Closing Express Server Instance
Closed Express Server Instance
Stopping Job Processing
2019-04-24T22:11:23.740Z agenda:stop Agenda.stop called, clearing interval for processJobs()
TypeError: Cannot read property '_processInterval' of undefined
    at module.exports (/app/node_modules/agenda/lib/agenda/stop.js:41:22)
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/app/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:443:21)
[nodemon] app crashed - waiting for file changes before starting...
```
("deleteme" is a dummy job)

- additional info:
```ts
// jobs/jobs.ts
export const jobs: Agenda = new Agenda({
    mongo: mongoose.connection.db,
    db: {
        collection: "jobs"
    },
    processEvery: 2 * 60 * 1000,
    maxConcurrency: 5
});
```

and in my "gracefull shutdown" promise chain 
```ts
// app.ts
.then((await import("./jobs/jobs")).jobs.stop)
```
(i load it dynamicly (await import()) because otherwise mongoose would not be connected when i would import it on top of the file)

**Comment by hasezoey** [comment]
Update: after `if (this && this._processInterval) {}` the next error is
```
TypeError: Cannot read property '_lockedJobs' of undefined
    at Promise (/app/node_modules/agenda/lib/agenda/stop.js:21:27)
    at new Promise (<anonymous>)
    at _unlockJobs (/app/node_modules/agenda/lib/agenda/stop.js:19:12)
    at module.exports (/app/node_modules/agenda/lib/agenda/stop.js:45:10)
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/app/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:443:21)
```

this seems like many "this" values are not defined when calling stop

**Comment by hasezoey** [comment]
i think it is / was a problem with bluebird
```ts
// app.ts
.then((await import("./jobs/jobs")).jobs.stop)
```
dosnt really work (dosnt wait for the previous promise to resolve & somehow deletes this?)
anyway this now works:
```ts
.then(async () => (await import("./jobs/jobs")).jobs.stop())
```
