### ISSUE TITLE
'clears locks on stop' test fails sometimes

### ISSUE THREAD

**Issue by dmbarreiro** [agenda/agenda#855]
'clears locks on stop' test case sometimes fails cause it is not able to find 'longRunningJob' on database, even though it should be there.

```
     ✓ clears locks on stop (2503ms)

      1) "after each" hook

  111 passing (21s)

  1 failing

  1) Job

       "after each" hook:

     Uncaught TypeError: Cannot read property 'lockedAt' of null

      at agenda._collection.findOne (test/job.js:630:20)

      at result (node_modules/mongodb/lib/utils.js:410:17)

      at session.endSession (node_modules/mongodb/lib/utils.js:398:11)

      at ClientSession.endSession (node_modules/mongodb-core/lib/sessions.js:134:41)

      at executeCallback (node_modules/mongodb/lib/utils.js:395:17)

      at handleCallback (node_modules/mongodb/lib/utils.js:128:55)

      at cursor.next (node_modules/mongodb/lib/operations/collection_ops.js:598:5)

      at result (node_modules/mongodb/lib/utils.js:410:17)

      at executeCallback (node_modules/mongodb/lib/utils.js:402:9)

      at handleCallback (node_modules/mongodb/lib/utils.js:128:55)

      at cursor._next (node_modules/mongodb/lib/operations/cursor_ops.js:195:5)

      at handleCallback (node_modules/mongodb-core/lib/cursor.js:204:5)

      at _setCursorNotifiedImpl (node_modules/mongodb-core/lib/cursor.js:426:38)

      at self._endSession (node_modules/mongodb-core/lib/cursor.js:434:46)

      at Cursor._endSession (node_modules/mongodb-core/lib/cursor.js:195:5)

      at Cursor._endSession (node_modules/mongodb/lib/cursor.js:231:59)

      at _setCursorNotifiedImpl (node_modules/mongodb-core/lib/cursor.js:434:17)

      at setCursorNotified (node_modules/mongodb-core/lib/cursor.js:426:3)

      at done (node_modules/mongodb-core/lib/cursor.js:650:16)

      at queryCallback (node_modules/mongodb-core/lib/cursor.js:701:18)

      at /home/travis/build/agenda/agenda/node_modules/mongodb-core/lib/connection/pool.js:397:18

      at process._tickCallback (internal/process/next_tick.js:61:11)
```

I do not have a solid theory on why is this happening but maybe we can try to increase jobTiemout when tests are executing on TravisCI (since I never had this problem running the tets on local). Submitted PR #852 (commit 23b40ef) with possible changes.

**Comment by dmbarreiro** [comment]
I suspect there was an await missing [here](https://github.com/agenda/agenda/pull/852/commits/387babfc171d8c5cfbfaf28764260ef919a16d28#r323423498), fixed in commit 387babf.

**Comment by sampathBlam** [comment]
@dmbarreiro : It seemed to have failed again in a recent PR #874 . 
Is it probably because the value of job becomes null/undefined, if a job with name 'longRunningJob' is not found 
`const job = await agenda._collection.findOne({name: 'longRunningJob'}); ` 
and in the next line we try to access `job.lockedAt` ?
