### ISSUE TITLE
Frequent error "Cannot read property 'attrs' of undefined" after updating from 2.1.0 to 2.2.0

### ISSUE THREAD

**Issue by kasia-sztymelska** [agenda/agenda#884]
Stack:
Unhandled rejection at: TypeError: Cannot read property 'attrs' of undefined
at Timeout.runOrRetry [as _onTimeout] (/usr/local/app/node_modules/agenda/lib/utils/process-jobs.js:228:47)
at ontimeout (timers.js:436:11)
at tryOnTimeout (timers.js:300:5)
at listOnTimeout (timers.js:263:5)
at Timer.processTimers (timers.js:223:10)

My config: 
    "maxConcurrency": 4,
    "defaultConcurrency": 1,
    "lockLimit": 4,
    "defaultLockLimit": 1,
    "defaultLockLifetime": 300000

**Comment by nealoke** [comment]
Same error here, the error also doesn't seem to be consistently triggered or caused. So when reque-ing a job 10x at once it will only trigger the error 5 times or 3 or none. 

![image](https://user-images.githubusercontent.com/17417414/69816823-770b9c80-11f9-11ea-98a9-25fa6a5e8d59.png)

**Comment by andreverbenergy** [comment]
I've been trying to debug this all morning as well. Line 228 of process-jobs.js relates to popping jobs from the queue. It seems to happen when there are jobs being run at the same time or very close to it, and the number of jobs being pushed into the queue doesn't line up with the number of jobs available to be popped. 

![image](https://user-images.githubusercontent.com/36932884/69818183-32b4d800-11ca-11ea-8f78-b4ed6c6754aa.png)

**Comment by JYF3721** [comment]
> Same error here, the error also doesn't seem to be consistently triggered or caused. So when reque-ing a job 10x at once it will only trigger the error 5 times or 3 or none.
> 
> Downgrading the version indeed resolves the error.
> 
> ![image](https://user-images.githubusercontent.com/17417414/69816823-770b9c80-11f9-11ea-98a9-25fa6a5e8d59.png)

Hello, I also encountered this problem in 2.0.2, exactly the same. What kind of version do you drop to Jia?

**Comment by koresar** [comment]
If someone would submit a PR I would try process it ASAP.

**Comment by Scorpil** [comment]
@koresar #886 
From what I could figure out, `jobProcessing` is executed twice on success (from `runOrRetry` and from `processJobResult`), which leads to double-scheduling for future job, which leads to an empty queue on a second call. Details in PR.

**Comment by mrcranky** [comment]
I can confirm that rolling back to 2.0.2 from 2.2.0 definitely does appear to make the issue go away.

I have two jobs, one every 10s and one every 60m, with a 15s interval. Every time the 60m job fired I would get the exception. Given the timings I'd expect that there to always be a 10s job to be processed in addition to the 60m job.

**Comment by hoangtrucit** [comment]
i have sample issue when upgrade from 2.0.2 to 2.2.0

**Comment by koresar** [comment]
Fixed with v.2.3.0
https://github.com/agenda/agenda/blob/master/History.md#230--2019-12-16

**Comment by themitchy** [comment]
We're seeing this right now in v3.1.0
Some regression re-introduce the problem?

**Comment by koresar** [comment]
Would you please show us the stack trace?

**Comment by rn2web** [comment]
(node:13472) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'attrs' of undefined
[0]     at line 63:22
[0]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[0] (Use `node --trace-warnings ...` to show where the warning was created)
[0] (node:13472) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[0] (node:13472) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
