### ISSUE TITLE
nodejs 6 compatibility ? 

### ISSUE THREAD

**Issue by kepkap** [agenda/agenda#916]
Hello, guys,

agenda job library fails on node6

The development was done on node8-10, very easy and successfully, BUT we faced unexpectedly old-timer node6 on target deployment servers. 

I am wondering if agenda has min node version requirement. 

Thanks
```
Jan 23 06:25:07 node-23e899a41f6e3e6d node: /opt/sococo/server/node_modules/agenda/lib/agenda/index.js:46
Jan 23 06:25:07 node-23e899a41f6e3e6d node: this._indices = {name: 1, ...this._sort, priority: -1, lockedAt: 1, nextRunAt: 1, disabled: 1};
Jan 23 06:25:07 node-23e899a41f6e3e6d node: ^^^
Jan 23 06:25:07 node-23e899a41f6e3e6d node: SyntaxError: Unexpected token ...
Jan 23 06:25:07 node-23e899a41f6e3e6d node: at createScript (vm.js:56:10)
Jan 23 06:25:07 node-23e899a41f6e3e6d node: at Object.runInThisContext (vm.js:97:10)
Jan 23 06:25:07 node-23e899a41f6e3e6d node: at Module._compile (module.js:549:28)
Jan 23 06:25:07 node-23e899a41f6e3e6d node: at Object.Module._extensions..js (module.js:586:10)
Jan 23 06:25:07 node-23e899a41f6e3e6d node: at Module.load (module.js:494:32)
Jan 23 06:25:07 node-23e899a41f6e3e6d node: at tryModuleLoad (module.js:453:12)
Jan 23 06:25:07 node-23e899a41f6e3e6d node: at Function.Module._load (module.js:445:3)
Jan 23 06:25:07 node-23e899a41f6e3e6d node: at Module.require (module.js:504:17)
Jan 23 06:25:07 node-23e899a41f6e3e6d node: at require (internal/module.js:20:19)
Jan 23 06:25:07 node-23e899a41f6e3e6d node: at Object.<anonymous> (/opt/sococo/server/node_modules/agenda/index.js:1:78)
Jan 23 06:25:07 node-23e899a41f6e3e6d node: at Module._compile (module.js:577:32)
Jan 23 06:25:07 node-23e899a41f6e3e6d node: at Object.Module._extensions..js (module.js:586:10)
Jan 23 06:25:07 node-23e899a41f6e3e6d node: at Module.load (module.js:494:32)
Jan 23 06:25:07 node-23e899a41f6e3e6d node: at tryModuleLoad (module.js:453:12)
Jan 23 06:25:07 node-23e899a41f6e3e6d node: at Function.Module._load (module.js:445:3)
Jan 23 06:25:07 node-23e899a41f6e3e6d node: at Module.require (module.js:504:17)
Jan 23 06:25:07 node-23e899a41f6e3e6d node: at require (internal/module.js:20:19)
Jan 23 06:25:07 node-23e899a41f6e3e6d node: at Object.<anonymous> (/opt/sococo/server/source/server/job/JobServiceFactory.js:45:14)
Jan 23 06:25:07 node-23e899a41f6e3e6d node: at Module._compile (module.js:577:32)
Jan 23 06:25:07 node-23e899a41f6e3e6d node: at Object.Module._extensions..js (module.js:586:10)
Jan 23 06:25:07 node-23e899a41f6e3e6d node: at Module.load (module.js:494:32)
Jan 23 06:25:07 node-23e899a41f6e3e6d node: at tryModuleLoad (module.js:453:12)
Jan 23 06:25:07 node-23e899a41f6e3e6d systemd: server.service: main process exited, code=exited, status=1/FAILURE
```

**Comment by OmgImAlexis** [comment]
6 is no longer maintained by node. You'll need to use something like babel if you still need to use an unsupported version of node.

![](https://raw.githubusercontent.com/nodejs/Release/master/schedule.svg?sanitize=true)

**Comment by kepkap** [comment]
Thank you @OmgImAlexis for quick response.
