### ISSUE TITLE
Cannot read property 'allConnections' of null

### ISSUE THREAD

**Issue by kiprobinson** [agenda/agenda#975]
I have seen this error twice now on long-running processes. Once it happens, agenda stops picking up any future tasks until the node process is restarted. I'm not sure what might be triggering it--the system is operating properly then it throws this error and stops working.

~~~
uncaughtException:  TypeError: Cannot read property 'allConnections' of null
    at Array.from.reduce (/workspace/node_modules/mongodb/lib/core/sdam/topology.js:249:42)
    at Array.reduce (<anonymous>)
    at NativeTopology.connections (/workspace/node_modules/mongodb/lib/core/sdam/topology.js:248:48)
    at Agenda.module.exports [as _findAndLockNextJob] (/workspace/sub-systems/scheduling-ms/node_modules/agenda/lib/agenda/find-and-lock-next-job.js:25:18)
    at jobQueueFilling (/workspace/sub-systems/scheduling-ms/node_modules/agenda/lib/utils/process-jobs.js:200:10)
    at Agenda.module.exports (/workspace/sub-systems/scheduling-ms/node_modules/agenda/lib/utils/process-jobs.js:32:9)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
~~~

This is on Agenda 2.0.6 and mongodb on 3.4.1. I have updated to Agenda 3.0.0 and mongodb 3.5.4 to see if the issue persists. But this is a pretty significant issue as it completely stops all tasks until the node process is restarted.

**Comment by mfauzaan** [comment]
How did you found this issue?
My worker is dying every 2-3 days, and when ever I check the logs there is no error shown

**Comment by kiprobinson** [comment]
I added an independent JS timer which runs every minute and checks if any Agenda jobs have completed in the last hour. If not, it assumes that the engine is dead and tries to create a new one. (We have several jobs that run every 5 minutes, so 1 hour without a job completing is definitely an error.)


```
setInterval(async () => {
    this.log.info('Checking if Agenda jobs engine is healthy');
    try {
        const db: Db = mongoose.connection;
        const n = await db.collection('agendaJobs').countDocuments({
            lastFinishedAt: {$gt: moment().add(-1, 'hour').toDate()}
        });
        if(n > 0) {
            this.log.info('Agenda jobs engine looks healthy');
        }
        else {
            this.log.warn('No jobs have completed in the last hour! Attempting to restart Agenda.');
            
            // Try to stop agenda in its own try/catch. If that fails, go on anyway
            // since next step is to create a new instance.
            try {
                await this.agenda.stop();
            }
            catch(err) {
                this.log.error('Error while stopping Agenda'); this.log.error(err);
            }
            
            this.agenda = new Agenda({mongo: mongoose.connection.collection('agendaJobs').conn.db, maxConcurrency: 1});
            await this.startAgenda();
        }
    }
    catch(err) {
        this.log.error('Error trying to check if Agenda is healthy');
        this.log.error(err);
    }
}, 60000);
```

**Comment by vivekmalumel** [comment]
But we alredy running agenda start on every 10 min
